on:
  push:
    branches:
      - '"main"'

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: 'us-central1'
  SERVICE: ${{ secret.SERVICE }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secret.WORKLOAD_IDENTITY_PROVIDER }} # projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  IMAGE: 'docker.io/bastilimbach/docker-magicmirror'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE }}
        image: ${{ env.IMAGE }}
        secrets: |-
          OPEN_WEATHER_MAP_LOCATION=${{ secrets.OPEN_WEATHER_MAP_LOCATION }}
          OPEN_WEATHER_MAP_LOCATION_ID=${{ secrets.OPEN_WEATHER_MAP_LOCATION_ID }}
          OPEN_WEATHER_MAP_API_KEY=${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
          CALENDAR_ICS_URL_PATH=${{ secrets.CALENDAR_ICS_URL_PATH }}