---
name: Server deploy
on:
  push:
    branches:
      - '"main"'
    paths:
      - 'server/**'

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: 'us-central1'
  SERVICE: ${{ secrets.SERVICE }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }} # projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE }}
        image: ghcr.io/${{ github.actor }}/${{ github.repository }}/mm-server
        secrets: |-
          OPEN_WEATHER_MAP_LOCATION=${{ secrets.OPEN_WEATHER_MAP_LOCATION }}
          OPEN_WEATHER_MAP_LOCATION_ID=${{ secrets.OPEN_WEATHER_MAP_LOCATION_ID }}
          OPEN_WEATHER_MAP_API_KEY=${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
          CALENDAR_ICS_URL_PATH=${{ secrets.CALENDAR_ICS_URL_PATH }}
